name = "Registry.jl"
uuid = "faae0330-ede6-4e42-8628-177ee811d5b1"
repo = "https://github.com/brewer-b/Registry.jl"
description = "My private Julia registry"

[packages]
133beed6-7c83-59bf-b8b3-f5e6e5f3f679 = { name = "PokerIsomorphism_jll", path = "jll/P/PokerIsomorphism_jll" }
cd065cc9-4ba2-5ee8-9ac0-d405a4942aee = { name = "OMPEval_jll", path = "jll/O/OMPEval_jll" }
